name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    container:
      openresty/openresty:centos

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      pebble:
        image: letsencrypt/pebble
        # command: pebble -config /test/my-pebble-config.json
        ports:
          - 14000:14000  # ACME port
          - 15000:15000  # Management port
        env:
          PEBBLE_VA_NOSLEEP: 1

    steps:
      - name: Run CURL
        run: |
          update-ca-trust enable
          mkdir -p /usr/share/ca-certificates/extra
          curl -k https://pebble:15000/roots/0 --output /usr/share/pki/ca-trust-source/pebble_root.ca
          update-ca-trust extract
          curl https://pebble:15000/roots/0



