name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    container:
      openresty/openresty:centos

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      pebble:
        image: letsencrypt/pebble
        # command: pebble -config /test/my-pebble-config.json
        ports:
          - 14000:14000  # ACME port
          - 15000:15000  # Management port
        env:
          PEBBLE_VA_NOSLEEP: 1

    steps:
      - name: Run CURL
        run: |
          echo -e >> /etc/ssl/certs/ca-certificates.crt
          curl https://raw.githubusercontent.com/letsencrypt/pebble/master/test/certs/pebble.minica.pem >> /etc/ssl/certs/ca-certificates.crt
          echo -e >> /etc/ssl/certs/ca-certificates.crt
          curl https://raw.githubusercontent.com/letsencrypt/pebble/master/test/certs/localhost/cert.pem >> /etc/ssl/certs/ca-certificates.crt
          curl https://raw.githubusercontent.com/letsencrypt/pebble/master/test/certs/localhost/cert.pem > /tmp/cert.pem
          echo hello
          curl --cacert /tmp/cert.pem https://pebble:15000/roots/0



